Added ko_kr.json
acikek/purpeille pull request #7
Opened 2022-07-16 13:39 UTC by rjuven2401

Translated most parts to Korean. Mistranslation and typos may exist.

2022-07-17 00:23 UTC, acikek requested changes

2022-07-17 00:23 UTC, acikek commented on src/main/resources/assets/purpeille/lang/ko_kr.json
> +}
Newline @ EOF

2022-07-17 00:23 UTC, acikek commented on src/main/resources/assets/purpeille/lang/ko_kr.json
> +    "patchouli.purpeille.ancients_almanac.landing_text": "고대의 비밀을 깨우쳐줄 개요서, $(italic)고대 역서$()",
You should keep this line as English, since the only translation of the guidebook is in English right now

2022-07-17 00:23 UTC, acikek commented on src/main/resources/assets/purpeille/lang/ko_kr.json
> +    "rite.purpeille.immersion": "Become deft yet determined.",
You can remove all translations that keep English text, as that's what the client defaults to. This goes for every English line, not just the highlighted ones

2022-07-18 11:03 UTC, rjuven2401 commented
Thank you! I will edit.

2022-07-18 11:07 UTC, rjuven2401 commented
Sorry I am not familiar with github so if it's not possible to merge then tell me, I will open a new pull request with edited file.

2022-07-19 16:41 UTC, acikek commented
No, this looks good, I'll merge

2022-07-19 16:41 UTC, acikek approved these changes

2022-07-19 16:41 UTC, merged